"use client";
import { Inter } from "next/font/google";
import "../globals.css";

import { useStore, AppState } from "../store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const content = useStore((state: AppState) => state.content) as string;

	return (
		<html lang="en">
			<body className={inter.className}>
				<h1>
					Hello {"some weirdo"} {content}
				</h1>

				{children}
			</body>
		</html>
	);
}
